apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uzgcf0wgj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uzgcf0wgj-go 
  name: uzgcf0wgj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uzgcf0wgj-go 
